#!/usr/bin/env bash

BASEDIR=$(dirname "$(readlink -f $0)")
MINTER_HOME=/home/minter
MINTER_SERVICE_NAME=minter-node
MINTER_GIT_REPO=https://api.github.com/repos/MinterTeam/minter-go-node
MINTER_GIT_DOWNLOAD=https://github.com/MinterTeam/minter-go-node
MINTER_LATEST_V=$(curl --silent "${MINTER_GIT_REPO}/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
MINTER_LATEST=${MINTER_LATEST_V:1}
RELIZE_FILE_ZIP=minter_${MINTER_LATEST}_linux_amd64.zip
DT_STAMP=$(date '+%d-%m-%Y_%H-%M')
LOG_FILE=${MINTER_HOME}/${DT_STAMP}_minter-update.log

clear
cd ${MINTER_HOME}

test -f ${BASEDIR}/.colors  && . ${BASEDIR}/.colors

# Ask SUDO permissions
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

# Ask confirmation
read -r -p "Are you sure want update Minter binary? [y/N] " response
if [[ !  "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    exit 0
fi

read -r -d '' MSG <<-EOM
${BLUE}#########################################################${NOCOLOR}

                ${YELLOW} Started ${MINTER_SERVICE_NAME} Update ${NOCOLOR}

${BLUE}#########################################################${NOCOLOR}
EOM

echo -e "${MSG}"

touch ${LOG_FILE}
#
# journalctl -u ${MINTER_SERVICE_NAME}  -n 100
# sudo systemctl status  ${MINTER_SERVICE_NAME}
# sudo systemctl start  ${MINTER_SERVICE_NAME}
# sudo systemctl restart  ${MINTER_SERVICE_NAME}

sudo systemctl stop  ${MINTER_SERVICE_NAME} &&
RESULT="${GREEN}[DONE] ${NOCOLOR}" || RESULT="${RED}[FAILED] ${NOCOLOR}"
        echo -e "${YELLOW}Stop Minter service. ${RESULT}"

# Remove old address book
test -f ${MINTER_HOME}/.minter/config/addrbook.json  && rm -f ${MINTER_HOME}/.minter/config/addrbook.json &>>${LOG_FILE}


# Backup configs
echo -e "
${MINTER_HOME}/.minter/config/
" > /tmp/minter_bcp.list

tar -czf  ${MINTER_HOME}/${DT_STAMP}_minter_bcp.tar.gz -T /tmp/minter_bcp.list &>>${LOG_FILE} &&
RESULT="${GREEN}[DONE] ${NOCOLOR}" || RESULT="${RED}[FAILED] ${NOCOLOR}"
        echo -e "${YELLOW}Backup Minter configs. ${RESULT}"

# Unlock sensitive files
test -f ${MINTER_HOME}/.minter  && sudo chattr -i ${MINTER_HOME}/.minter

# Download latest release
wget --no-check-certificate --content-disposition ${MINTER_GIT_DOWNLOAD}/releases/download/${MINTER_LATEST_V}/${RELIZE_FILE_ZIP} -O ${RELIZE_FILE_ZIP}  &>>${LOG_FILE} &&
unzip -o  ${RELIZE_FILE_ZIP}  &>>${LOG_FILE} &&
chmod 755 ${MINTER_HOME}/minter &&
chown minter:minter ${MINTER_HOME}/minter &&
RESULT="${GREEN}[DONE] ${NOCOLOR}" || RESULT="${RED}[FAILED] ${NOCOLOR}"
        echo -e "${YELLOW}Latest (${MINTER_LATEST_V}) release got. ${RESULT}"


# Lock sensitive files
test -f ${MINTER_HOME}/.minter  && sudo chattr +i ${MINTER_HOME}/.minter

# test -f ${MINTER_HOME}/${RELIZE_FILE_ZIP} && rm -f ${MINTER_HOME}/${RELIZE_FILE_ZIP} &>>${LOG_FILE}


#
sudo systemctl start  ${MINTER_SERVICE_NAME}  &>>${LOG_FILE} &&
RESULT="${GREEN}[DONE] ${NOCOLOR}" || RESULT="${RED}[FAILED] ${NOCOLOR}"
        echo -e "${YELLOW}Start Minter service. ${RESULT}"

#Halth check
#curl http://127.0.0.1:8841/api/status | json_pp &>> ${LOG_FILE}
